package com.example.playmaker.code;

import lombok.Getter;

import java.util.ArrayList;
import java.util.List;

import static com.example.playmaker.cmn.Const.*;


@Getter
public enum ActiveArea {

    SEOUL(SEOUL_CODE, SEOUL_NAME, null),
    GANGNAM(GANGNAM_CODE, GANGNAM_NAME, SEOUL),
    GANGDONG(GANGDONG_CODE, GANGDONG_NAME, SEOUL),
    GANGBUK(GANGBUK_CODE, GANGBUK_NAME, SEOUL),
    GANGSU(GANGSU_CODE, GANGSU_NAME, SEOUL),
    GWANAK(GWANAK_CODE, GWANAK_NAME, SEOUL),
    GWANGJIN(GWANGJIN_CODE, GWANGJIN_NAME, SEOUL),
    GURO(GURO_CODE, GURO_NAME, SEOUL),
    GEUMCHEON(GEUMCHEON_CODE, GEUMCHEON_NAME, SEOUL),
    NOWON(NOWON_CODE, NOWON_NAME, SEOUL),
    DOBONG(DOBONG_CODE, GANGDONG_NAME, SEOUL),
    DONGDAEMUN(DONGDAEMUN_CODE, DONGDAEMUN_NAME, SEOUL),
    DONGJAK(DONGJAK_CODE, DONGJAK_NAME, SEOUL),
    MAPO(MAPO_CODE, MAPO_NAME, SEOUL),
    SEODAEMUN(SEODAEMUN_CODE, SEODAEMUN_NAME, SEOUL),
    SEOCHO(SEOCHO_CODE, SEOCHO_NAME, SEOUL),
    SEONGDONG(SEONGDONG_CODE, SEONGDONG_NAME, SEOUL),
    SEONGBUK(SEONGBUK_CODE, SEONGBUK_NAME, SEOUL),
    SONGPA(SONGPA_CODE, SONGPA_NAME, SEOUL),
    YANGCHUN(YANGCHUN_CODE, YANGCHUN_NAME, SEOUL),
    YEONGDEUNGPO(YEONGDEUNGPO_CODE, YEONGDEUNGPO_NAME, SEOUL),
    YONGSAN(YONGSAN_CODE, YONGSAN_NAME, SEOUL),
    EUNPYEONG(EUNPYEONG_CODE, EUNPYEONG_NAME, SEOUL),
    JONGRO(JONGRO_CODE, JONGRO_NAME, SEOUL),
    JUNGGUO(JUNGGU_CODE, JUNGGU_NAME, SEOUL),
    JUNGRANG(JUNGRANG_CODE, JUNGRANG_NAME, SEOUL),

    GYEONGGI(GYEONGGI_CODE, GYEONGGI_NAME, null),
    GAPYEONG(GAPYEONG_CODE, GAPYEONG_NAME, GYEONGGI),
    GOYANG_DUKYANG(GOYANG_DUKYANG_CODE, GOYANG_DUKYANG_NAME, GYEONGGI),
    GOYANG_ILSANDONG(GOYANG_ILSANDONG_CODE, GOYANG_ILSANDONG_NAME, GYEONGGI),
    GOYANG_ILSANSU(GOYANG_ILSANSU_CODE, GOYANG_ILSANSU_NAME, GYEONGGI),
    GHACHUN(GHACHUN_CODE, GHACHUN_NAME, GYEONGGI),
    GHYANGMYONG(GHYANGMYONG_CODE, GHYANGMYONG_NAME, GYEONGGI),
    GHYANGCHU(GHYANGCHU_CODE, GHYANGCHU_NAME, GYEONGGI),
    GURI(GURI_CODE, GURI_NAME, GYEONGGI),
    GUNPO(GUNPO_CODE, GUNPO_NAME, GYEONGGI),
    GIMPO(GIMPO_CODE, GIMPO_NAME, GYEONGGI),
    NAMYANGCHU(NAMYANGCHU_CODE, NAMYANGCHU_NAME, GYEONGGI),
    DONGDUCHUN(DONGDUCHUN_CODE, DONGDUCHUN_NAME, GYEONGGI),
    BUCHUN_SOSA(BUCHUN_SOSA_CODE, BUCHUN_SOSA_NAME, GYEONGGI),
    BUCHUN_OJUNG(BUCHUN_OJUNG_CODE, BUCHUN_OJUNG_NAME, GYEONGGI),
    BUCHUN_ONEMI(BUCHUN_ONEMI_CODE, BUCHUN_ONEMI_NAME, GYEONGGI),
    SUNGNAM_BUNDANG(SUNGNAM_BUNDANG_CODE, SUNGNAM_BUNDANG_NAME, GYEONGGI),
    SUNGNAM_SUJUNG(SUNGNAM_SUJUNG_CODE, SUNGNAM_SUJUNG_NAME, GYEONGGI),
    SUNGNAM_CHUNGWON(SUNGNAME_CHUNGWON_CODE, SUNGNAME_CHUNGWON_NAME, GYEONGGI),
    SUWON_KOWNSUN(SUWON_KOWNSUN_CODE, SUWON_KOWNSUN_NAME, GYEONGGI),
    SUWON_YUNGTONG(SUNWON_YUNGTONG_CODE, SUNWON_YUNGTONG_NAME, GYEONGGI),
    SUWON_JANGAN(SUWON_JANGAN_CODE, SUWON_JANGAN_NAME, GYEONGGI),
    SUWON_PALDAL(SUWON_PALDAL_CODE, SUWON_PALDAL_NAME, GYEONGGI),
    SIHEUNG(SIHEUNG_CODE, SIHEUNG_NAME, GYEONGGI),
    ANSAN_DANWON(ANSAN_DANWON_CODE, ANSAN_DANWON_NAME, GYEONGGI),
    ANSAN_SANGROK(ANSAN_SANGROK_CODE, ANSAN_SANGROK_NAME, GYEONGGI),
    ANSUNG(ANSUNG_CODE, ANSUNG_NAME, GYEONGGI),
    ANYANG_DONGAN(ANYANG_DONGAN_CODE, ANYANG_DONGAN_NAME, GYEONGGI),
    ANYANG_MANAN(ANYANG_MANAN_CODE, ANYANG_MANAN_NAME, GYEONGGI),
    YANGCHU(YANGCHU_CODE, YANGCHU_NAME, GYEONGGI),
    YANGPYEONG(YANGPYEONG_CODE, YANGPYEONG_NAME, GYEONGGI),
    YEOJU(YEOJU_CODE, YEOJU_NAME, GYEONGGI),
    YEONCHUN(YEONCHUN_CODE, YEONCHUN_NAME, GYEONGGI),
    OSAN(OSAN_CODE, OSAN_NAME, GYEONGGI),
    YONGIN_KIHEUNG(YONGIN_KIHEUNG_CODE, YONGIN_KIHEUNG_NAME, GYEONGGI),
    YONGIN_SUJI(YONGIN_SUJI_CODE, YONGIN_SUJI_NAME, GYEONGGI),
    YONGIN_CHUIN(YONGIN_CHUIN_CODE, YONGIN_CHUIN_NAME, GYEONGGI),
    UIWANG(UIWANG_CODE, UIWANG_NAME, GYEONGGI),
    UIJUNGBU(UIJUNGBU_CODE, UIJUNGBU_NAME, GYEONGGI),
    ECHUN(ECHUN_CODE, ECHUN_NAME, GYEONGGI),
    PAJU(PAJU_CODE, PAJU_NAME, GYEONGGI),
    PYENGTAEK(PYENGTAEK_CODE, PYENGTAEK_NAME, GYEONGGI),
    POCHUN(POCHUN_CODE, POCHUN_NAME, GYEONGGI),
    HANAM(HANAM_CODE, HANAM_NAME, GYEONGGI),
    HWASUNG(HWASUNG_CODE, HWASUNG_NAME, GYEONGGI),

    INCHEON(INCHEON_CODE, INCHEON_NAME, null),
    GANGHWA(GANGHWA_CODE, GANGHWA_NAME, INCHEON),
    GYEYANG(GYEYANG_CODE, GYEYANG_NAME, INCHEON),
    MICHUHOL(MICHUHOL_CODE, MICHUHOL_NAME, INCHEON),
    NAMDONGGU(NAMDONGGU_CODE, NAMDONGGU_NAME, INCHEON),
    DONGGU(DONGGU_CODE, DONGGU_NAME, INCHEON),
    BUPYEONG(BUPYEONG_CODE, BUPYEONG_NAME, INCHEON),
    SEOGU(SEOGU_CODE, SEOGU_NAME, INCHEON),
    YEONSU(YEONSU_CODE, YEONSU_NAME, INCHEON),
    ONGJIN(ONGJIN_CODE, ONGJIN_NAME, INCHEON),
    JUNGGU2(JUNGGU2_CODE, JUNGGU2_NAME, INCHEON);


    private final Long key;
    private final String value;
    private final ActiveArea parent;

    private final List<ActiveArea> children = new ArrayList<>();

    ActiveArea(Long key, String value, ActiveArea parent) {
        this.key = key;
        this.value = value;
        this.parent = parent;
        if (this.parent != null) {
            this.parent.addChild(this);
        }
    }

    private void addChild(ActiveArea child) {
        for (ActiveArea a = this; a != null; a = a.parent) {
            a.children.add(child);
        }
    }

    public List<ActiveArea> children() {
        return this.children;
    }


    public static ActiveArea of(Long areaCd) {
        if (areaCd == null) {
            throw new IllegalArgumentException();
        }

        for (ActiveArea a : ActiveArea.values()) {
            if (a.key.equals(areaCd)) {
                return a;
            }
        }

        throw new IllegalArgumentException("일치하는 지역코드가 없습니다.");
    }
}
